Add missing global 'security' declaration to openapi.proto
authzed/api pull request #120
Opened 2024-11-07 06:39 UTC by holgerstolzenberg

Fixes ApiKeyAuth method being used by clients generated via OpenAPI generator.

Original idea: https://github.com/authzed/authzed-go/pull/255

2024-11-08 15:20 UTC, tstirrat15 commented
Gonna have a look at this today. Thanks for putting it up!

2024-11-08 15:21 UTC, tstirrat15 commented
How does it differ from what's right above it? https://github.com/authzed/api/pull/120/files#diff-2c89108fef442d02f29499535203f20595b6fdd3cff830a5b3fd40e979eece0bR34-R41

2024-11-08 16:38 UTC, holgerstolzenberg commented
Okay maybe I have messed up the syntax a bit. Let's take it different, as I am not familiar with `buf`.

This is what the target swagger.json should look like:

<img width="2523" alt="Screenshot 2024-11-08 at 17 33 53" src="https://github.com/user-attachments/assets/7d78d485-c72d-46bd-98f6-3a4b80c0d066">

I have updated the PR, hope that makes more sense now.

2024-11-08 20:49 UTC, tstirrat15 commented
Hmm... the thing I'm getting hung up on is that there's two `security` blocks. Is that correct/expected? Should we change the existing `security` block rather than adding a new one?

2024-11-09 09:08 UTC, holgerstolzenberg commented
No I think this is totally fine - even if not being really straight forward at fist. The official docs unfortunately use yaml for examples already.

So you have essentially two elements:

`securityDefinitions` defines what is actually _available_ from your API, but it does not apply that auth method to anywhere.
Here it just says: The API supports an Authentication **named** `ApiKeyAuth` that is of type `apiKey` and will be applied by using a _header_ named `Authorization`.

In the `security` section you just name _where_ your defined security methods are going to be applied by just cross referencing them. Line `3035` means, take the auth method named `ApiKey` and then apply it to all endpoints (`[]`).

Even if that looks unfamiliar, it is confirmed working. So you might want to take a look here:
https://github.com/ewerk/authzed-http-client/blob/fc74dc40f8d81720f976b1d866106d4e8907bfed/.github/workflows/main-build.yml#L34

2024-11-12 11:04 UTC, vroldanbet requested changes
Thanks for your contribution, I have two comments, otherwise LGTM

2024-11-12 12:17 UTC, holgerstolzenberg commented on authzed/api/v1/openapi.proto
> +	},
Repository local `.gitignore` dropped, as request, though I do not like the global config approach. Have it in the repo, you have it controlled for everyone contributing, no matter what their env is. Even if that means duplicating the file to each repo.

Description added as requested.

2024-11-12 12:18 UTC, holgerstolzenberg commented on .gitignore
> +.idea/
Repository local `.gitignore` dropped, as request, though I do not like the global config approach. Have it in the repo, you have it controlled for everyone contributing, no matter what their env is. Even if that means duplicating the file to each repo.

2024-11-12 12:23 UTC, vroldanbet approved these changes

2024-11-12 13:36 UTC, holgerstolzenberg commented
@tstirrat15 Could you also please review - I am not able to request that and it seems like a second review is required.

2024-11-12 14:54 UTC, tstirrat15 commented
Yep, this makes sense now. Thank you!

2024-11-12 14:54 UTC, tstirrat15 approved these changes

2024-11-12 14:55 UTC, tstirrat15 commented
Before I merge this I'm going to try pulling it into authzed-go as a SHA and see if the openapi definition makes sense.

2024-11-12 16:30 UTC, tstirrat15 commented
I checked this out and it looks good. I'm going to go ahead and merge this, and then I'll do the work to pull it into authzed-go.

2024-11-12 16:33 UTC, merged